<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (ORGID?,FLATUID?,INOPERUID?,INVNUMBER?,KODREG?,PREVADDRESS?,PURPOSEUID?,PURPOSECOMMENT?,SQUARE?,ROOMSCOUNT?,FLOOR?,FLATNAME?,REMARKIN?,OUTOPERUID?,REMARKOUT?,NUMCOMPLEX?,ORGUID?,PAGENUM?,BSQUARE?,BPURPOSEUID?,WALLTYPEUID?,INDATE?,FLOORS?,BUILDNAME?,DOCTYPEUID?,IDRIGHTTYPE?,RIGHTTYPEREMARK?,DATESTART?,DATEEND?,OPERDATE?,DECLDATE?,PRICEVALUE?,CURRENCYTYPE?,ADDRESSUID?,SOATO?,OBJECTNUMBER?,PRICEVALUEUSD?,PRICEDESCR?,DOCUMUID?,AUTHENTIC?,XRECOUNT?,YRECOUNT?,OPERUID?,REGCODE?,DETAILPARCEL?,PARCELUID?,PINOPERUID?,NEWRECORD?,BUILDINGUID?,COUNTPARCELS?,PBLOCK?,PPURPOSEUID?,PSQUARE?,PARCELNUMBER?,PRINTMARK?,SOATO_1?,BLDINV?,DOL?)+>
  <!ELEMENT ORGID (#PCDATA)>
  <!ELEMENT FLATUID (#PCDATA)>
  <!ELEMENT INOPERUID (#PCDATA)>
  <!ELEMENT INVNUMBER (#PCDATA)>
  <!ELEMENT KODREG (#PCDATA)>
  <!ELEMENT PREVADDRESS (#PCDATA)>
  <!ELEMENT PURPOSEUID (#PCDATA)>
  <!ELEMENT PURPOSECOMMENT (#PCDATA)>
  <!ELEMENT SQUARE (#PCDATA)>
  <!ELEMENT ROOMSCOUNT (#PCDATA)>
  <!ELEMENT FLOOR (#PCDATA)>
  <!ELEMENT FLATNAME (#PCDATA)>
  <!ELEMENT REMARKIN (#PCDATA)>
  <!ELEMENT OUTOPERUID (#PCDATA)>
  <!ELEMENT REMARKOUT (#PCDATA)>
  <!ELEMENT NUMCOMPLEX (#PCDATA)>
  <!ELEMENT ORGUID (#PCDATA)>
  <!ELEMENT PAGENUM (#PCDATA)>
  <!ELEMENT BSQUARE (#PCDATA)>
  <!ELEMENT BPURPOSEUID (#PCDATA)>
  <!ELEMENT WALLTYPEUID (#PCDATA)>
  <!ELEMENT INDATE (#PCDATA)>
  <!ELEMENT FLOORS (#PCDATA)>
  <!ELEMENT BUILDNAME (#PCDATA)>
  <!ELEMENT DOCTYPEUID (#PCDATA)>
  <!ELEMENT IDRIGHTTYPE (#PCDATA)>
  <!ELEMENT RIGHTTYPEREMARK (#PCDATA)>
  <!ELEMENT DATESTART (#PCDATA)>
  <!ELEMENT DATEEND (#PCDATA)>
  <!ELEMENT OPERDATE (#PCDATA)>
  <!ELEMENT DECLDATE (#PCDATA)>
  <!ELEMENT PRICEVALUE (#PCDATA)>
  <!ELEMENT CURRENCYTYPE (#PCDATA)>
  <!ELEMENT ADDRESSUID (#PCDATA)>
  <!ELEMENT SOATO (#PCDATA)>
  <!ELEMENT OBJECTNUMBER (#PCDATA)>
  <!ELEMENT PRICEVALUEUSD (#PCDATA)>
  <!ELEMENT PRICEDESCR (#PCDATA)>
  <!ELEMENT DOCUMUID (#PCDATA)>
  <!ELEMENT AUTHENTIC (#PCDATA)>
  <!ELEMENT XRECOUNT (#PCDATA)>
  <!ELEMENT YRECOUNT (#PCDATA)>
  <!ELEMENT OPERUID (#PCDATA)>
  <!ELEMENT REGCODE (#PCDATA)>
  <!ELEMENT DETAILPARCEL (#PCDATA)>
  <!ELEMENT PARCELUID (#PCDATA)>
  <!ELEMENT PINOPERUID (#PCDATA)>
  <!ELEMENT NEWRECORD (#PCDATA)>
  <!ELEMENT BUILDINGUID (#PCDATA)>
  <!ELEMENT COUNTPARCELS (#PCDATA)>
  <!ELEMENT PBLOCK (#PCDATA)>
  <!ELEMENT PPURPOSEUID (#PCDATA)>
  <!ELEMENT PSQUARE (#PCDATA)>
  <!ELEMENT PARCELNUMBER (#PCDATA)>
  <!ELEMENT PRINTMARK (#PCDATA)>
  <!ELEMENT SOATO_1 (#PCDATA)>
  <!ELEMENT BLDINV (#PCDATA)>
  <!ELEMENT DOL (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>402</FLATUID>
    <INOPERUID>7246</INOPERUID>
    <INVNUMBER>166</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;.&#1087;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1042;&#1086;&#1083;&#1086;&#1076;&#1072;&#1088;&#1089;&#1082;&#1086;&#1075;&#1086;, &#1076;. 37, &#1082;&#1074;. 29</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>60,2</SQUARE>
    <ROOMSCOUNT>3</ROOMSCOUNT>
    <FLOOR>0</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 60,2 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 38,2 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>56901</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>3826</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <INDATE>1984/01/01 00:00:00</INDATE>
    <FLOORS>5</FLOORS>
    <BUILDNAME>70 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1087;&#1103;&#1090;&#1080;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2015/05/07 10:01:00</OPERDATE>
    <DECLDATE>1992/02/22 00:00:00</DECLDATE>
    <PRICEVALUE>9401</PRICEVALUE>
    <CURRENCYTYPE>999</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>9401</PRICEVALUEUSD>
    <DOCUMUID>3642</DOCUMUID>
    <OPERUID>180597</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>328</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>122</BUILDINGUID>
    <PBLOCK>0</PBLOCK>
    <PPURPOSEUID>10902</PPURPOSEUID>
    <PSQUARE>1</PSQUARE>
    <PARCELNUMBER>143</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-30</BLDINV>
    <DOL>1/2</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>402</FLATUID>
    <INOPERUID>56901</INOPERUID>
    <INVNUMBER>166</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1042;&#1086;&#1083;&#1086;&#1076;&#1072;&#1088;&#1089;&#1082;&#1086;&#1075;&#1086;, 37-29</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>60,2</SQUARE>
    <ROOMSCOUNT>3</ROOMSCOUNT>
    <FLOOR>2</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 60,2 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 38,2 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>2</PAGENUM>
    <BSQUARE>3826</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <INDATE>1984/01/01 00:00:00</INDATE>
    <FLOORS>5</FLOORS>
    <BUILDNAME>70 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1087;&#1103;&#1090;&#1080;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/05/07 10:01:00</OPERDATE>
    <DECLDATE>1992/02/22 00:00:00</DECLDATE>
    <PRICEVALUE>9401</PRICEVALUE>
    <CURRENCYTYPE>999</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>9401</PRICEVALUEUSD>
    <DOCUMUID>3642</DOCUMUID>
    <OPERUID>180597</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>328</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>122</BUILDINGUID>
    <PBLOCK>0</PBLOCK>
    <PPURPOSEUID>10902</PPURPOSEUID>
    <PSQUARE>1</PSQUARE>
    <PARCELNUMBER>143</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-30</BLDINV>
    <DOL>1/2</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>13650</FLATUID>
    <INOPERUID>128955</INOPERUID>
    <INVNUMBER>2201</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1051;&#1077;&#1085;&#1080;&#1085;&#1089;&#1082;&#1072;&#1103;, 11-6</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>41,3</SQUARE>
    <ROOMSCOUNT>2</ROOMSCOUNT>
    <FLOOR>2</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#8470;6</FLATNAME>
    <REMARKIN>&#1044;&#1074;&#1091;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 41,3 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; 30,6 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>0</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>7</WALLTYPEUID>
    <FLOORS>2</FLOORS>
    <BUILDNAME>8 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1082;&#1080;&#1088;&#1087;&#1080;&#1095;&#1085;&#1099;&#1081; &#1076;&#1074;&#1091;&#1093;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/02/09 11:08:00</OPERDATE>
    <DECLDATE>2016/02/02 00:00:00</DECLDATE>
    <PRICEVALUE>441126000</PRICEVALUE>
    <CURRENCYTYPE>1</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>24013</PRICEVALUEUSD>
    <DOCUMUID>128393</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>175358</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>3756</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>2567</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>-1</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>266</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-659</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>3483</FLATUID>
    <INOPERUID>43883</INOPERUID>
    <INVNUMBER>1262</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1047;&#1077;&#1083;&#1105;&#1085;&#1072;&#1103;, 13-2</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>80,4</SQUARE>
    <ROOMSCOUNT>4</ROOMSCOUNT>
    <FLOOR>2</FLOOR>
    <FLATNAME>&#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1095;&#1077;&#1090;&#1099;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1095;&#1077;&#1090;&#1099;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 80,4 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 51,6 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>159,7</BSQUARE>
    <BPURPOSEUID>21102</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <FLOORS>1</FLOORS>
    <BUILDNAME>&#1086;&#1076;&#1085;&#1086;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/03/16 15:45:00</OPERDATE>
    <DECLDATE>2016/02/16 00:00:00</DECLDATE>
    <PRICEVALUE>61000000</PRICEVALUE>
    <CURRENCYTYPE>1</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>63201</PRICEVALUEUSD>
    <DOCUMUID>129474</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>176963</OPERUID>
    <REGCODE>1616</REGCODE>
    <PARCELUID>7979</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>6971</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>-1</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>932</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-3810</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>749</FLATUID>
    <INOPERUID>8703</INOPERUID>
    <INVNUMBER>338</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1042;&#1086;&#1083;&#1086;&#1076;&#1072;&#1088;&#1089;&#1082;&#1086;&#1075;&#1086;, 48-15</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>52,2</SQUARE>
    <ROOMSCOUNT>2</ROOMSCOUNT>
    <FLOOR>3</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1076;&#1074;&#1091;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1076;&#1074;&#1091;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 52,2 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 30,1 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>1156</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <INDATE>1992/01/01 00:00:00</INDATE>
    <FLOORS>5</FLOORS>
    <BUILDNAME>20 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081; &#1087;&#1103;&#1090;&#1080;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/03/24 14:27:00</OPERDATE>
    <DECLDATE>2016/03/24 00:00:00</DECLDATE>
    <PRICEVALUE>100000000</PRICEVALUE>
    <CURRENCYTYPE>1</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>5444</PRICEVALUEUSD>
    <DOCUMUID>129851</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>177648</OPERUID>
    <REGCODE>1616</REGCODE>
    <PARCELUID>2910</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>1722</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>-1</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>224</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-140</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>2817</FLATUID>
    <INOPERUID>37406</INOPERUID>
    <INVNUMBER>1208</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1051;&#1077;&#1085;&#1080;&#1085;&#1089;&#1082;&#1072;&#1103;, 11-2</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>41,1</SQUARE>
    <ROOMSCOUNT>2</ROOMSCOUNT>
    <FLOOR>1</FLOOR>
    <FLATNAME>&#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1076;&#1074;&#1091;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1076;&#1074;&#1091;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 41,1 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 29,0 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>0</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>7</WALLTYPEUID>
    <FLOORS>2</FLOORS>
    <BUILDNAME>8 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1082;&#1080;&#1088;&#1087;&#1080;&#1095;&#1085;&#1099;&#1081; &#1076;&#1074;&#1091;&#1093;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/04/30 10:09:00</OPERDATE>
    <DECLDATE>2016/04/30 00:00:00</DECLDATE>
    <PRICEVALUE>518778000</PRICEVALUE>
    <CURRENCYTYPE>1</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>28241</PRICEVALUEUSD>
    <DOCUMUID>130774</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>180320</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>3756</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>2567</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>-1</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>266</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-659</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>10332</FLATUID>
    <INOPERUID>105708</INOPERUID>
    <INVNUMBER>1839</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1050;&#1072;&#1083;&#1075;&#1091;&#1096;&#1082;&#1080;&#1085;&#1072;, &#1076;. 15-2</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>130,8</SQUARE>
    <ROOMSCOUNT>5</ROOMSCOUNT>
    <FLOOR>1</FLOOR>
    <FLATNAME>&#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1087;&#1103;&#1090;&#1080;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1087;&#1103;&#1090;&#1080;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 130,8 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 83,5 &#1082;&#1074;.&#1084;. &#1089; &#1075;&#1072;&#1088;&#1072;&#1078;&#1086;&#1084; &#1082;&#1080;&#1088;&#1087;&#1080;&#1095;&#1085;&#1099;&#1084; &#40;5&#41;, , &#1089;&#1072;&#1088;&#1072;&#1077;&#1084; &#1082;&#1080;&#1088;&#1087;&#1080;&#1095;&#1085;&#1099;&#1084; &#40;6&#41;, &#1091;&#1073;&#1086;&#1088;&#1085;&#1072;&#1103; &#1082;&#1080;&#1088;&#1087;&#1080;&#1095;&#1085;&#1072;&#1103; &#40;7&#41;</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>260</BSQUARE>
    <BPURPOSEUID>21103</BPURPOSEUID>
    <WALLTYPEUID>7</WALLTYPEUID>
    <INDATE>1981/01/01 00:00:00</INDATE>
    <FLOORS>1</FLOORS>
    <BUILDNAME>&#1086;&#1076;&#1085;&#1086;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084; &#1082;&#1080;&#1088;&#1087;&#1080;&#1095;&#1085;&#1099;&#1081;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/05/28 11:16:00</OPERDATE>
    <DECLDATE>2016/05/28 00:00:00</DECLDATE>
    <PRICEVALUE>100000000</PRICEVALUE>
    <CURRENCYTYPE>1</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>5444</PRICEVALUEUSD>
    <DOCUMUID>131496</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>181281</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>18214</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>16948</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>-1</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>1656</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-6943</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>1847</FLATUID>
    <INOPERUID>184771</INOPERUID>
    <INVNUMBER>89</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1042;&#1086;&#1083;&#1086;&#1076;&#1072;&#1088;&#1089;&#1082;&#1086;&#1075;&#1086;, &#1076;. 39&#1040;-31</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>70,5</SQUARE>
    <ROOMSCOUNT>3</ROOMSCOUNT>
    <FLOOR>4</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 70,5 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 44,3 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>-1</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>2</PAGENUM>
    <BSQUARE>2041,5</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <FLOORS>5</FLOORS>
    <BUILDNAME>35 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1087;&#1103;&#1090;&#1080;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/07/19 16:29:00</OPERDATE>
    <DECLDATE>2016/07/19 00:00:00</DECLDATE>
    <PRICEVALUE>60000</PRICEVALUE>
    <CURRENCYTYPE>933</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>60000</PRICEVALUEUSD>
    <DOCUMUID>133006</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>184823</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>1770</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>683</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>10900</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>152</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-164</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>1847</FLATUID>
    <INOPERUID>12584</INOPERUID>
    <INVNUMBER>89</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1041;&#1072;&#1088;&#1072;&#1085;&#1086;&#1074;&#1082;&#1072;, 39&#1072;-31</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>70,5</SQUARE>
    <ROOMSCOUNT>3</ROOMSCOUNT>
    <FLOOR>4</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 70,5 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 44,3 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>184771</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>2041,5</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <INDATE>1982/01/01 00:00:00</INDATE>
    <FLOORS>5</FLOORS>
    <BUILDNAME>35 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1087;&#1103;&#1090;&#1080;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/07/19 16:29:00</OPERDATE>
    <DECLDATE>2016/07/19 00:00:00</DECLDATE>
    <PRICEVALUE>60000</PRICEVALUE>
    <CURRENCYTYPE>933</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>60000</PRICEVALUEUSD>
    <DOCUMUID>133006</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>184823</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>1770</PARCELUID>
    <NEWRECORD>1</NEWRECORD>
    <BUILDINGUID>683</BUILDINGUID>
    <PBLOCK>1</PBLOCK>
    <PPURPOSEUID>10900</PPURPOSEUID>
    <PSQUARE>0</PSQUARE>
    <PARCELNUMBER>152</PARCELNUMBER>
    <SOATO_1>4246501000</SOATO_1>
    <BLDINV>442/C-164</BLDINV>
    <DOL>1/1</DOL>
  </DATA_RECORD>
  <DATA_RECORD>
    <ORGID>442</ORGID>
    <FLATUID>1847</FLATUID>
    <INOPERUID>12584</INOPERUID>
    <INVNUMBER>89</INVNUMBER>
    <PREVADDRESS>&#1043;&#1088;&#1086;&#1076;&#1085;&#1077;&#1085;&#1089;&#1082;&#1072;&#1103; &#1086;&#1073;&#1083;., &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;&#1082;&#1080;&#1081; &#1088;-&#1085;, &#1075;. &#1054;&#1089;&#1090;&#1088;&#1086;&#1074;&#1077;&#1094;, &#1091;&#1083;. &#1041;&#1072;&#1088;&#1072;&#1085;&#1086;&#1074;&#1082;&#1072;, 39&#1072;-31</PREVADDRESS>
    <PURPOSEUID>40101</PURPOSEUID>
    <PURPOSECOMMENT>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072;</PURPOSECOMMENT>
    <SQUARE>70,5</SQUARE>
    <ROOMSCOUNT>3</ROOMSCOUNT>
    <FLOOR>4</FLOOR>
    <FLATNAME>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103;</FLATNAME>
    <REMARKIN>&#1050;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1072; &#1090;&#1088;&#1077;&#1093;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1085;&#1072;&#1103; &#1086;&#1073;&#1097;&#1077;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; &#1078;&#1080;&#1083;&#1099;&#1093; &#1087;&#1086;&#1084;&#1077;&#1097;&#1077;&#1085;&#1080;&#1081; 70,5 &#1082;&#1074;.&#1084;., &#1078;&#1080;&#1083;&#1086;&#1081; &#1087;&#1083;&#1086;&#1097;&#1072;&#1076;&#1100;&#1102; 44,3 &#1082;&#1074;.&#1084;.</REMARKIN>
    <OUTOPERUID>184771</OUTOPERUID>
    <ORGUID>442</ORGUID>
    <PAGENUM>1</PAGENUM>
    <BSQUARE>2041,5</BSQUARE>
    <BPURPOSEUID>21101</BPURPOSEUID>
    <WALLTYPEUID>11</WALLTYPEUID>
    <FLOORS>5</FLOORS>
    <BUILDNAME>35 &#1082;&#1074;&#1072;&#1088;&#1090;&#1080;&#1088;&#1085;&#1099;&#1081; &#1087;&#1103;&#1090;&#1080;&#1101;&#1090;&#1072;&#1078;&#1085;&#1099;&#1081; &#1087;&#1072;&#1085;&#1077;&#1083;&#1100;&#1085;&#1099;&#1081; &#1078;&#1080;&#1083;&#1086;&#1081; &#1076;&#1086;&#1084;</BUILDNAME>
    <DOCTYPEUID>3301</DOCTYPEUID>
    <IDRIGHTTYPE>1000</IDRIGHTTYPE>
    <OPERDATE>2016/07/19 16:29:00</OPERDATE>
    <DECLDATE>2016/07/19 00:00:00</DECLDATE>
    <PRICEVALUE>60000</PRICEVALUE>
    <CURRENCYTYPE>933</CURRENCYTYPE>
    <SOATO>4246551000</SOATO>
    <OBJECTNUMBER>15116</OBJECTNUMBER>
    <PRICEVALUEUSD>60000</PRICEVALUEUSD>
    <DOCUMUID>133006</DOCUMUID>
    <XRECOUNT>0</XRECOUNT>
    <YRECOUNT>0</YRECOUNT>
    <OPERUID>184823</OPERUID>
    <REGCODE>504</REGCODE>
    <PARCELUID>1770</PARCELUID>
    <NEWRECORD>1</NEWRECORD>